# Generated by Django 5.2.1 on 2025-06-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_dish_desired_ready_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='desired_ready_time',
        ),
        migrations.AddField(
            model_name='order',
            name='desired_ready_time',
            field=models.DateTimeField(blank=True, help_text='Опционально: укажите дату и время готовности', null=True, verbose_name='Время, к которому блюдо должно быть готово'),
        ),
    ]
