# Generated by Django 5.2.1 on 2025-06-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Подтвержден'), ('in_progress', 'В процессе'), ('ready', 'Готово')], default='confirmed', max_length=12, verbose_name='Статус блюда'),
        ),
    ]
