# Generated by Django 5.2.1 on 2025-06-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Заполняется только если статус = "rejected"', verbose_name='Причина отказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Новый'), ('accepted', 'Принят'), ('rejected', 'Отклонён'), ('in_progress', 'В процессе'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='pending', max_length=15, verbose_name='Статус'),
        ),
    ]
