# Generated by Django 5.2.1 on 2025-06-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_rejection_reason_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='desired_ready_time',
            field=models.DateTimeField(blank=True, help_text='Опционально: укажите дату и время готовности', null=True, verbose_name='Время, к которому блюдо должно быть готово'),
        ),
    ]
