# Generated by Django 5.2.1 on 2025-06-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_dish_desired_ready_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_dishes',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='api.dish', verbose_name='Избранные блюда'),
        ),
    ]
